[package]
name = "rbw"
version = "1.4.3"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = "2018"

description = "Unofficial Bitwarden CLI"
repository = "https://git.tozt.net/rbw"
readme = "README.md"
keywords = ["bitwarden"]
categories = ["command-line-utilities", "cryptography"]
license = "MIT"
include = ["src/**/*", "bin/**/*", "LICENSE", "README.md", "CHANGELOG.md"]

[dependencies]
aes = "0.7.5"
anyhow = "1.0.53"
arrayvec = "0.7.2"
async-trait = "0.1.52"
base32 = "0.4.0"
base64 = "0.13.0"
block-modes = "0.8.1"
block-padding = "0.2.1"
daemonize = "0.4.1"
directories = "4.0.1"
env_logger = "0.9.0"
hkdf = "0.11.0"
hmac = { version = "0.11.0", features = ["std"] }
humantime = "2.1.0"
libc = "0.2.117"
log = "0.4.14"
nix = "0.23.1"
paw = "1.0.0"
pbkdf2 = "0.9.0"
percent-encoding = "2.1.0"
rand = "0.8.4"
region = "3.0.0"
reqwest = { version = "0.11.9", default-features = false, features = ["blocking", "json", "rustls-tls-native-roots"] }
rsa = "0.5.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
serde_path_to_error = "0.1.7"
serde_repr = "0.1.7"
sha-1 = "0.9.8"
sha2 = "0.9.9"
structopt = { version = "0.3.26", features = ["paw", "wrap_help"] }
tempfile = "3.3.0"
term_size = "0.3.2"
textwrap = "0.11.0"
thiserror = "1.0.30"
tokio = { version = "1.16.1", features = ["full"] }
totp-lite = "1.0.3"
url = "2.2.2"
uuid = { version = "0.8.2", features = ["v4"] }
zeroize = "1.4.3"

[package.metadata.deb]
depends = "pinentry"
license-file = ["LICENSE"]
assets = [
    ["target/release/rbw", "usr/bin/", "755"],
    ["target/release/rbw-agent", "usr/bin/", "755"],
    ["target/release/completion/bash", "usr/share/bash-completion/completions/rbw", "644"],
    ["target/release/completion/zsh", "usr/share/zsh/vendor-completions/_rbw", "644"],
    ["target/release/completion/fish", "usr/share/fish/completions/rbw.fish", "644"],
    ["README.md", "usr/share/doc/rbw/README", "644"],
]
